CORRIDOR_GRAPH = {
    "Airport New South Road": ["ORR North 1", "Hennur Main Road", "Old Madras Road", "Bellary Road 2"],
    "Bannerghata Road": ["Hosur Road", "ORR West 1", "IRR(Thanisandra road)"],
    "Bellary Road 1": ["CBD 2", "Non-corridor", "ORR North 2", "Hennur Main Road"],
    "Bellary Road 2": ["Hennur Main Road", "ORR North 2", "Airport New South Road"],
    "CBD 1": ["Non-corridor", "CBD 2", "Old Madras Road"],
    "CBD 2": ["Non-corridor", "CBD 1", "Old Madras Road", "Bellary Road 1", "Mysore Road", "West of Chord Road"],
    "Hennur Main Road": ["Airport New South Road", "ORR North 1", "Bellary Road 1", "Bellary Road 2"],
    "Hosur Road": ["IRR(Thanisandra road)", "Bannerghata Road", "ORR East 1"],
    "IRR(Thanisandra road)": ["Hosur Road", "Old Airport Road", "ORR East 1", "Bannerghata Road"],
    "Magadi Road": ["West of Chord Road", "Tumkur Road", "Mysore Road"],
    "Mysore Road": ["West of Chord Road", "ORR West 1", "CBD 2", "Magadi Road"],
    "Non-corridor": ["CBD 2", "CBD 1", "Old Madras Road", "Bellary Road 1"],
    "ORR East 1": ["Old Airport Road", "IRR(Thanisandra road)", "Hosur Road", "ORR East 2", "Varthur Road"],
    "ORR East 2": ["Varthur Road", "Old Airport Road", "ORR East 1"],
    "ORR North 1": ["Airport New South Road", "Hennur Main Road", "Old Madras Road"],
    "ORR North 2": ["Tumkur Road", "Bellary Road 1", "West of Chord Road", "Bellary Road 2"],
    "ORR West 1": ["Mysore Road", "Bannerghata Road", "West of Chord Road"],
    "Old Airport Road": ["ORR East 1", "ORR East 2", "Old Madras Road", "IRR(Thanisandra road)", "Varthur Road"],
    "Old Madras Road": ["CBD 1", "Non-corridor", "CBD 2", "Airport New South Road", "ORR North 1", "Old Airport Road"],
    "Tumkur Road": ["ORR North 2", "Magadi Road", "West of Chord Road"],
    "Varthur Road": ["ORR East 2", "Old Airport Road", "ORR East 1"],
    "West of Chord Road": ["Magadi Road", "Mysore Road", "CBD 2", "ORR North 2", "ORR West 1", "Tumkur Road"]
}